// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Mid1YWTDRHNp_eh8MWGdGakWFqlzi4I',
    appId: '1:210405420126:web:67cd1691d9528f706698cf',
    messagingSenderId: '210405420126',
    projectId: 'project-3-luluah',
    authDomain: 'project-3-luluah.firebaseapp.com',
    storageBucket: 'project-3-luluah.appspot.com',
    measurementId: 'G-GKQ26KC1WM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLiYwXkRB2TV5vUL29QaJ0OHqNC9WH6_k',
    appId: '1:210405420126:ios:2fad927cfede637c6698cf',
    messagingSenderId: '210405420126',
    projectId: 'project-3-luluah',
    storageBucket: 'project-3-luluah.appspot.com',
    iosClientId: '210405420126-8lq1jd3i107982d6ehuu3jop72j72p2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.thechefz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLiYwXkRB2TV5vUL29QaJ0OHqNC9WH6_k',
    appId: '1:210405420126:ios:2fad927cfede637c6698cf',
    messagingSenderId: '210405420126',
    projectId: 'project-3-luluah',
    storageBucket: 'project-3-luluah.appspot.com',
    iosClientId: '210405420126-8lq1jd3i107982d6ehuu3jop72j72p2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.thechefz',
  );
}
